# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4ad41028e52bd5d0e4fc3106067e7610fec3d1940af32655418ea1f6ae46126e4b55321447901999f369cfd64dcf7f6782f958749e66cc32e473c4dc9cce3ce

test:
  secret_key_base: b035a88ac9f2802df9cf491b7b6800dacc50525ec6c439e1dca7711cc751aea39b54e77fb169dc48ee9aebeef59107a9d7ddc06e1e18af910605a35737160e5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
